- name: Join Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Check if the node is already part of the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Fetch join command from control node
      ansible.builtin.slurp:
        src: "/tmp/join_command.txt"
      delegate_to: localhost
      run_once: true
      register: join_command_file
      when: not kubelet_conf.stat.exists

    - name: Convert join command to string
      ansible.builtin.set_fact:
        join_command: "{{ join_command_file['content'] | b64decode | trim }}"
      when: not kubelet_conf.stat.exists

    - name: Join Kubernetes cluster
      ansible.builtin.command: "{{ join_command }}"
      when: not kubelet_conf.stat.exists
    
    - name: Assign label "worker" to nodes
      ansible.builtin.command: "kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker="
      delegate_to: master
      run_once: false
